### ISSUE TITLE
ジョブの基礎DATA率見直しまたはLB DATA別途加算機能の作成

### ISSUE THREAD

**Issue by kitsuki00** [MotocalDevelopers/motocal#104]
#102 にて基礎TA率の修正をしましたが、
現状の基礎DATA率にはLBが加算されたものとされていないもの、混ざっています。
LB分のDATAを別途加算する仕組みを作るか、値の見直しが必要かと思います。
上記別途加算の仕組みを作成する場合、Class4及びEx2の基礎TA率はLBを引いたものに
再修正が必要です。

**Comment by kagekiyo7** [comment]
LBではなくLVアップボーナスのことでしょうか？

現在引用させていただいているのはこの二方の検証ですが、ひろ氏はボーナス込みと明言しています。
すんどめ侍氏は特に言及していませんが、オーガの基礎DA率60％にボーナス分20%上乗せするとレスラーの70%を超えてしまうのでボーナス込みかと思われます。なので特に問題はないかと。
http://hiroxgbf.blog.fc2.com/blog-entry-39.html
http://greatsundome.hatenablog.com/entry/2015/10/11/175521
