### ISSUE TITLE
キャラ基礎連撃率

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#129]
表記は(DA, TA)

基本的に検証勢が提唱した
10,5 / 7,3 / 4,1 / 特殊 のグループ分けを採用

デフォルト(未記入)は7,3

----

> DA率＝DA回数/(攻撃回数-TA回数)

https://twitter.com/konmatsuge/status/868322459929288704

----

~~最終十天~~
https://twitter.com/usa_akasa/status/1048885872416907264

~~水属性SSR~~
https://twitter.com/takeshi310310/status/1048812912347774976

~~火属性SSR~~
https://twitter.com/takeshi310310/status/1045698942820790274

**Comment by Groovman** [comment]
👍  will take a look at it

**Comment by kagekiyo7** [comment]
光属性SSR
https://twitter.com/usa_akasa/status/1095981859073253377

**Comment by kagekiyo7** [comment]
風ヘルエス、風ユエル、土ダーント、エウロペ
https://twitter.com/KST33166653/status/1109847251407392774

**Comment by kagekiyo7** [comment]
アラナン
https://twitter.com/takeshi310310/status/1112321459244822530

**Comment by kagekiyo7** [comment]
ガイゼンボーガ
https://twitter.com/damfonmgg/status/1123072454128050176
