### ISSUE TITLE
以前の元カレ計算機で作成した編成を読み込むと画面が真っ白になる

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#138]
更新前の元カレ計算機([gbf-tool氏](https://gbf-tool.com/motocal/)のもので確認)で作成したシエテ(最終前、後どちらも)が入った編成データを、現在の元カレ計算機([ミムメモ速報氏](https://medon-lab.com/keisanki/)のもので確認)で読み込むと画面が真っ白になります。
現在の元カレ計算機で編成を作り直せばいいのですが、一応報告。

環境：Win10
ブラウザ：Google Chrome beta、Google Chrome、Firefoxで確認
編成データ：https://www.axfc.net/u/3962284
(test1が以前、test2が現在)

追記：
サポアビをnoneに書き換えたら読み込めるようになりました。
未登録のサポアビIDを読み込むと真っ白になるようです。

**Comment by kei-gbf** [comment]
サポアビの識別子名が変更された為に起こっていたようですね。編成データの互換性問題。

サイトに反映された日はいつか解りませんが、コードの変更日時は (github 上から "Blame" で確認)
4属性最終十天の与ダメUPサポアビが奥義上限に対応してる箇所で、識別子名も変更
https://github.com/Groovman/motocal/commit/28a15ffc0ba58da26d5e9de0a34158f320992e2e

データの互換性の対応については、"none"として読み込んで後から手作業で再設定する事も出来ますが
この辺りは編成データの仕様を把握してないと難しそうなので、作り直した方が早くて確実。

元カレ側でも未登録のサポアビIDでエラーが出ないようにはした方が良さそうなので調べてみます。
