### ISSUE TITLE
ガンダゴウザのサポートアビリティ修正

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#140]
全体風DA率UP10%となっていますが、格闘キャラDA率10%UPです。

Support Abi.1 of Ghandagoza is mistake

**Comment by kei-gbf** [comment]
現行のリポジトリ( MotocalDevelopers/motocal master )にはなかったので、
PR #132 か Groovman のリポジトリのようですね。
表示のみの問題で、実装は拳得意のみに掛かる様になっているのを確認しました。

@Groovman 
Can you fix the Japanese text in your repo.
Ghandagoza's da_up_fist_10's name field was Kokkoro's copy (全体風 mean was wind characters)
The support ability description should be DA up for fist type characters.

```JSON
    "da_up_fist_10": {
        "name": "格闘キャラDA率10%UP(ガンダゴウザ)",
        "type": "daBuff_fist",
        "range": "all",
        "value": 0.10
    },
```

I could not find the translation in src/translate.js file.
