### ISSUE TITLE
自動更新OFF時に武器の削除をすると画面が真っ白になる

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#141]
武器詳細からの削除、武器一覧の下からの削除両方から確認。

**Comment by kei-gbf** [comment]
Chromeで画面が白くなる原因を確認しました。

取り急ぎ、JavaScriptのエラー原因を取り除いたのみで、
Motocal が自動更新offの時どういう挙動をするのが正しいのかは把握してません。
識者の方、#143のテストとレビューお願いします

[English info]
I confirmed the screen white out on Chrome.
I just debug JavaScript programming error.
I am not familiar with how Motocal system should behave on non auto update mode.
Please test and review #143

**Comment by gin0606** [comment]
取り急ぎの js のエラー回避という目的なら問題無さそうに見えるので該当 PR mergeしちゃいますね
