### ISSUE TITLE
名称変更「ゼニスパーク」

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#145]
ゼニスパークという呼び方は古いので主人公リミットボーナスに名前を変えてもいいのではないでしょうか。

ゼニス攻撃力 → 攻撃力
ゼニスHP → HP
武器ゼニス → 得意武器攻撃
味方HPゼニス → 味方全体HP

**Comment by kei-gbf** [comment]
ユーザに表示されるテキストのみの変更ですが、PR 投げておきました。

追記: 表示文字の変更だけなら src/translate.js のみで良かったかもしれない。

**Comment by kagekiyo7** [comment]
感謝です。
