### ISSUE TITLE
敵防御固有値に説明を追加

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#147]
例：
敵防御5(通常敵 デバフ下限)
敵防御7(マグナⅡ光闇 デバフ下限)
敵防御8(マグナⅡ4属性 デバフ下限)
敵防御10(通常敵 デバフ無し)(ﾏﾘｽ/ｱｰｶｰｼｬ デバフ下限)
敵防御11(プロバハN デバフ無し)
敵防御13(マグナⅡ4属性 デバフ無し)
敵防御20(召喚石HL/プロバハHL デバフ無し)

現状ではない値ですが、この3つを追加してもいいかもしれません。
敵防御7.5(通常敵 デバフ25%)
敵防御6(通常古戦場HELL/アルバハHL デバフ下限)
敵防御15(召喚石HL/強バハHL デバフ下限)

防御値はここを参考にしたので誤っている可能性もあります。
https://kamigame.jp/%E3%82%B0%E3%83%A9%E3%83%96%E3%83%AB/%E3%82%B2%E3%83%BC%E3%83%A0%E7%9F%A5%E8%AD%98/%E3%83%9E%E3%83%AB%E3%83%81%E3%83%90%E3%83%88%E3%83%AB%E9%98%B2%E5%BE%A1%E5%80%A4%E4%B8%80%E8%A6%A7.html

**Comment by kei-gbf** [comment]
防御デバフは減算なのでしょうか？
トライアルでしか試したことなかったので下限 x 0.5だと思ってた。

もし可能ならだけど、敵防御値とデバフの項目は別々にした方が
色々な組み合わせに対応しやすそうです。他には、

- [ ] 喪失枠
- [ ] 属性ダウンでアタッカーが属性混合編成の場合
  他属性のダメージを含めて厳密に計算したい場合は少ないとは思いますが、
  個人的に気になった点。

メモを兼ねて作業タスク洗い出しておきます。

- [ ] 表示文字の変更
  - src/translate.js の 敵防御～ で追記可能
- [ ] 新たな防御値を追加
  - src/global_const.js の enemyDefenseType へ追加する。translate.js にも合わせて追加
- [ ] 敵防御値とデバフの項目を分ける → ダメージ計算や入力項目の追加などの対応が必要
- [ ] 属性ダウンは6属性分の項目を追加するは(あまり需要がないのに対し)複雑になるので、
      実装としてはキャラ個別に属性ダウンの項目を持たせる等。（実装案のみメモ）

**Comment by kei-gbf** [comment]
今 src/translate.js を確認したのだけど、敵防御に防御固有値やデバフ等の説明が書かれてました。
もしかすると、説明は書かれてあるけど表示に反映されてないって問題なのかな・・・？！

**Comment by kei-gbf** [comment]
翻訳リソース内に敵防御値の説明はありましたが、
日本語ロケールでは翻訳されず表示されていませんでした。
英語や中国語では防御値の一覧で敵やデバフの説明が書かれていたようです。

上記PRでは日本語ロケールでの防御値の翻訳のみ対応してます。

提案にあった説明文の変更や追加は行っていません。
（元からあった翻訳データを表示します）

**Comment by kagekiyo7** [comment]
すみません。こちらの理解が間違っていました。防御固有値×0.5が下限ですね。

>｛ 防御固有値 × ( 1 ＋ 敵防御力UPバフ ー 敵防御力DOWNデバフ ー 敵属性耐性DOWNデバフ ）*a ｝
>http://gbf-wiki.com/index.php?%A5%B7%A5%B9%A5%C6%A5%E0%BB%C5%CD%CD%B4%D8%CF%A2

色々追加するとゴチャゴチャしてしまうので難しいところですね。理想は防御固有値(敵種)とデバフ量の2つのドロップダウンメニューを設置することなんでしょうけど。

同じ値を複数置いていいのなら以下のはどうでしょうか。

敵防御4(通常敵)(デバフ下限+喪失枠)
敵防御5(通常敵)(デバフ下限)
敵防御7.5(通常敵)(デバフ25%)
敵防御10(通常敵)(デバフなし)
敵防御4.4(通常古戦場HELL/ｱﾙﾊﾞﾊHL/ﾌﾟﾛﾊﾞﾊN)(デバフ下限+喪失枠)
敵防御5.5(通常古戦場HELL/ｱﾙﾊﾞﾊHL/ﾌﾟﾛﾊﾞﾊN)(デバフ下限)
敵防御11(通常古戦場HELL/ｱﾙﾊﾞﾊHL/ﾌﾟﾛﾊﾞﾊN)(デバフなし)
敵防御4.8(マグナⅡ光闇/マグナHL/黄黒HL)(デバフ下限+喪失枠)
敵防御6(マグナⅡ光闇/マグナHL/黄黒HL)(デバフ下限)
敵防御12(マグナⅡ光闇/マグナHL/黄黒HL)(デバフなし)
敵防御5.2(マグナⅡ4属性)(デバフ下限+喪失枠)
敵防御6.5(マグナⅡ4属性)(デバフ下限)
敵防御13(マグナⅡ4属性)(デバフなし)
敵防御5.6(フレイ)(デバフ下限+喪失枠)
敵防御7(フレイ)(デバフ下限)
敵防御14(フレイ)(デバフなし)
敵防御6(ﾏﾘｽ/ｱｰｶｰｼｬ)(デバフ下限+喪失枠)
敵防御7.5(ﾏﾘｽ/ｱｰｶｰｼｬ)(デバフ下限)
敵防御15(ﾏﾘｽ/ｱｰｶｰｼｬ)(デバフなし)
敵防御8(召喚石HL/プロバハHL)(デバフ下限+喪失枠)
敵防御10(召喚石HL/プロバハHL)(デバフ下限)
敵防御20(召喚石HL/プロバハHL)(デバフなし)

**Comment by kei-gbf** [comment]
## 敵防御値のリストへ重複する値の追加

同じ値で別の表示というのは、現在の仕組みでは対応できなさそうです。

ドロップダウンの仕組み的には、同じ値を複数持っても良いのですが、
元カレのプログラム内部で区別ができない問題。

現状の敵防御のドロップダウン表示部分は、以下のような流れで

1. 編成データとして 10 (数値)を持っている場合、
2. 翻訳のIDとなる "敵防御10" を参照し (src/global_consts.js)
3. 翻訳される言語に応じたテキストを探し出す (src/translate.js)

仕組み自体を変更して対応することは可能ですが、
他へ影響がでる可能性がある為、安易に仕様変更できない部分があります。

例えば、現在の保存される編成データでは  "enemyDefense": 10 と数値のみで保持しているので、
デバフなしなのかプロバハのデバフ下限が区別できなく、これに対応しようと
編成データの仕様を変更した場合、過去の編成データが読み込めなくなるといった感じ。

いっその事、数値を直接記入出来るようにして
入力補完でリストから選択も出来る形式がいいのかな。

----
## リストにない値の追加に関して

よく使う値を追加して欲しいという利便性の改善ではないけど、
敵防御固有値のリストにない値で試算してみたい場合の対応策
以下の手順で出来そうです。

- データ出力
- "enemyDefense" の値を書き換え
- データ入力
- 読込

計算結果に手入力した防御値が反映されるのは確認。
正しい演算結果かどうかは未検証。

他に、開発者向けになりますが、頻繁に値を書き換え試してみたい場合は、
「React Developer Tools」というブラウザ拡張を使う手段もあります。（軽く紹介のみ）

----
## 敵防御値とデバフ量を同一項目にする際の問題点

例えばデバフの数値をひとつ追加する度に
現状でも敵防御の数(7) x 翻訳の数("ja", "en", "zh" の3つ) の21も追加が必要になるので
保守性に優れないという問題があります。

新たな防御値の敵や他の言語への翻訳が増えた場合にも、作業量が多くなってしまうので
出来れば、敵防御とデバフ量は別項目にする方向で調べてみます。

但し、編成データの仕様変更や、サーバへの保存なんかが絡んでくると
自分はそこまで把握できてないので、もし時間がかかりそうなら
暫定的に追加してみて、将来的に敵防御とデバフの項目を別ける。

**Comment by kei-gbf** [comment]
敵防御を直接入力とリストから選択の両方可能にしてみました。(敵防御のみの部分的なデモ)
幾つか課題はあるけど見た目は良い感じ。

![敵防御選択入力の動作デモ](https://user-images.githubusercontent.com/45387555/55664229-1b556300-5866-11e9-9b12-c276502a7bbd.PNG)

ブラウザ上での動作デモ: https://codepen.io/anon/pen/axZVZE?editors=1111

**Comment by kagekiyo7** [comment]
ありがとうございます。
手持ちのブラウザで試してみました。取り敢えず推奨環境のPC版Chromeでは問題なく使えてるのでいいのではないでしょうか。

・Chrome
問題なし

・Chrome beta
説明が出てこない
![image](https://user-images.githubusercontent.com/22173829/55668152-7906a100-58a0-11e9-8d49-b68a060cf1f3.png)

・iPhone (Safari, Chrome) / Firefox
入力補完そのものが出てこない

**Comment by kei-gbf** [comment]
テストありがとう。
これで入力された値の補完ではなく、常に全部の項目を表示してくれればいいのだけど。
現状では、ブラウザの実装依存の他、初期値を設定した時に意図した挙動にならない為、
一旦、保留としますね。

見た目は上記のようなものを目指して、
恐らく、他の方法で実装することになると思います。

**Comment by kei-gbf** [comment]
敵防御値の選択＆入力のデモ2 (Comboboxのライブラリ利用)
https://codepen.io/anon/pen/vMKrEZ?editors=0011

ライブラリの試用ついでにデバフも選択にしてみたけど、これはまた別として、
デモはこれで最後にしておきます＞敵防御値の直接入力

----
複数のトピックがあるのでまとめ。

- [x] 敵防御値に説明を出す #148
  - [x] 他の防御値、翻訳に関して #149 
- [ ] 敵防御値とデバフ量の分離 #149
- [ ] 敵防御値を入力可能にする (TODO)
