### ISSUE TITLE
優先度の低い手間のかかる要望一覧

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#151]
殆ど妄想メモですが、実現してくださる方がいらっしゃいましたら是非…

- [ ] 表示する項目の「キャラ奥義ダメージ」「キャラ単攻撃ダメージ(技巧連撃無)」「キャラ予想ターンダメージ」「チェインバースト」数値を減衰の域に応じて色分け(黒→黄緑→黄→橙→赤など)

- [ ] 表示する項目のに↑それぞれの減衰値の表示項目を追加

- [ ] 表示する項目の「スキル合計の数値」が上限に達していたら色を付ける(DATAだけ?)

- [x] 優先項目「奥義ダメージ」にチェインバーストが考慮されていないので計算に加える(もしくは新しく「奥義ダメージ＋チェインバースト」を作る)

- [ ] LB/指輪理想算出(現状の編成で火力に寄与する順のLB/指輪効果を出力)
2個分の指輪の効果を入力してどちらのほうがいいか比較するなんてのも

- [ ] 予想ターン毎ダメージを1T辺りの連撃硬直時間で割った値での理想「DSP編成(奥義硬直未考慮)」
(そこに入力ターンの予測チェイン回数分の奥義硬直も加えられたらさらにいい)
>基本ターン経過1秒にプラスして、攻撃回数*0.35秒
https://www65.atwiki.jp/matakamiesobu/pages/95.html
>奥義硬直
>https://twitter.com/jeffreymanson/status/869847039013670912

- [ ] バフプリセット(自分で設定、保存できるように)

- [ ] 武器詳細に「メインで持つ」チェックボックスの設置(ONでジータさん奥義倍率変更＋メイン時のみのスキルを有効に)

- [ ] 武器詳細にプラスボーナス欄の設置と武器一括プラスボーナス付与機能(現状だと＋を変えるのに武器を入れ直さなきゃならないので)

- [x] キャラの「+300」対応

- [ ] 任意のキャラ詳細にチェックボックス設置(「1アビの～バフ適応」「奥義時の～効果適応」「モードチェンジ(サラーサやメイドなどの奥義効果切り替え)」など)

- [ ] 奥義ゲージ200%の対応(奥義ソート時奥義ダメージに2回分反映、ゲージ100%で溢れてしまわないので奥義回転率が若干高い)

- [ ] クロスフェイトのATK、HP上昇対応(素のステータスを変更するか、キャラ詳細にチェックボックス作成)
http://gbf-wiki.com/index.php?%A5%AF%A5%ED%A5%B9%A5%D5%A5%A7%A5%A4%A5%C8%A5%A8%A5%D4%A5%BD%A1%BC%A5%C9%B0%EC%CD%F7

- [ ] 武器詳細の該当武器スキルの下に「○ターン目」の項目(ターン経過で増減するスキルに対応)

- [x] 英語版UI調整(日本語より文が長いので左メニューをもう少し広げるor文字の短縮or文字サイズの縮小)

- [ ] サポアビなどまだ訳されていない部分の英訳

- [x] [英語での説明書](https://www.reddit.com/r/Granblue_en/comments/7df4hr/i_tried_making_a_guide_on_how_to_use_motocal/)を見つけたのでリンクする(許可貰いました)

- [x] 更新履歴を最新の3~5個のみ表示し後は畳む

- [x] 要望フォームは機能しているか確認

- [x] このGithubのwiki開設(試験的に)(細かい仕様などメモ＆共有できたらなと)

- [ ] 背水渾身グラフでここをクリックすると画面いっぱいに編成一覧が開き閉じられなくなる
![image](https://user-images.githubusercontent.com/22173829/56080948-5f3a0080-5e42-11e9-84a6-682c35e7aec5.png)
- [ ] ↑の編成一覧の表示位置をずらせないので文の後半が見えない
※「保存された編成を編集」から名前を付けるのが前提の機能みたいなのでデフォルトでもっと短い名前を付けたほうがよさそう(どんな名前がいいかは思い浮かばない)

- [ ] グラフクリック時の説明に数字の前に"HP"文字を加え、ダメージ量も加える
![image](https://user-images.githubusercontent.com/22173829/56080986-f99a4400-5e42-11e9-869b-cf9281aa3934.png)

- [ ] キャラ一覧に画像がない場合判別に困るのでレアリティと属性を追加する
https://i.imgur.com/F7lLP3o.png

- [ ] 武器一覧を名前以外でももう少し絞れるようにする(武器種、レアリティ、シリーズ等)

- [x] 「キャラ情報・スキル合計値」からキャラ奥義ダメージを選択するとキャラターン毎の奥義上昇量も選択される(反映はされていない)

- [x] 「キャラ情報・スキル合計値」から何か選択をした後キャラターン毎の奥義上昇量を選択しても選択されない(反映はしている)

- [ ] 奥義ゲージ上昇量の変動がスキル合計に表示されない

- [ ] ジータ、キャラ、武器タブで詳細を開いて下にスクロールした時に名前が常に一番上にくるようにする
![image](https://user-images.githubusercontent.com/22173829/56232263-4b4d0380-60bb-11e9-88c5-b43b32df2662.png)

- [ ] Groovman氏の英語コメントアウトと従来の日本語コメントアウトを共存できるようにする(手動で足してもいいのですが、何かいい方法はないでしょうか)

- [ ] 十天衆を総べし者称号の効果

- [ ] 検索時にひらがなとカタカナを区別しないようにする

- [ ] アップデートがあったことを分かりやすくするために新しいキャラ武器が上にくるように(前まで出来てたけど仕様変更で変わった(?))

- [ ] スキル名でも検索できるように(前まで出来てたけど仕様変更で変わった(?))

- [ ] デフォルトでの2つ目の召喚石を削除する(重くなる)

- [x] キャラLB の % 表示を他と揃える (関連 #207)

- [ ] グラブルの表示攻撃力に合わせた普通の「攻撃力」とスキル込の「基礎ダメージ」で表示項目を分ける

- [ ] 奥義ゲージ増加時の端数対応
http://i-never.blog.jp/archives/9433609.html

- [ ] 英語名前被り対応
![image](https://user-images.githubusercontent.com/22173829/58874365-9b336880-8703-11e9-8e92-7e25cb7225cd.png)

- [ ] 英語スキル効果量表示時突き抜け対応
![image](https://user-images.githubusercontent.com/22173829/58935888-6a0d7380-87a9-11e9-86c5-b78b4f7aaa97.png)

- [ ] 武器の数が多いと重くなるので処理軽量化(可能?)

- [ ] 「平均に含める」チェックボックスを外してもスキル合計表示に含まれてしまうので対応

- [ ] 言語設定をクッキーかなにかに保存する

- [ ] 選択ジョブの得意武器を1つは必ず含めて計算するかどうかのチェックボックス(二刀クリュは2つ)

- [ ] ジータLBを★タイプに表記統一
![image](https://user-images.githubusercontent.com/22173829/58875210-e0f13080-8705-11e9-8a62-99d494c4086c.png)

- [ ] どれが追加されているかわかりにくいので、グラフの「追加」をチェックボックスに

- [ ] スキル表示の表記揺れ解決 https://github.com/MotocalDevelopers/motocal/pull/301

- [ ] 平均に含めるをOFFにしたキャラが表示される。(計算も不要？)
![image](https://user-images.githubusercontent.com/22173829/61312378-4838ef00-a833-11e9-87c0-f3a577891cb5.png)

- [ ] 新しい編成算出方法。実際のグラブルをシミュレーションして確率が収束すると言われている10000ターンくらいのダメージを計測しそれをソートキーにする。物凄い計算に時間が掛かりそう

- [ ] javascriptの小数問題解消
https://qiita.com/k_moto/items/0b576a3351b77fb0aa98
ライブラリ
https://qiita.com/daikw/items/663bc0b5a4c025694974

- [ ] global_logic.test.jsに通常のダメージ計算と背水渾身グラフのダメージ計算が合致するかのtestを追加

- [ ] キャラごとに特有のフィールドを持たせる(アンチラなら葦編三絶のチェックボックス、ブロディアなら刃鏡数のコンボボックスなど)

**Comment by kei-gbf** [comment]
凄い、計算機を使い込んでる！全部の担当表明は出来ませんが、
連休に時間取れれば、一つづつ個別に見ていきたいと思います。

----
各タスクのリスト表記関して
リストの頭の点・ですが、- [ ] に表記の変更お願いできますか

- [ ] ←チェックボックス

```
- [ ] ←チェックボックス
```

GithubのIssue tracker の機能で
1番最初のコメント内にチェックボックスがあると、
issueの一覧でチェック個数を確認できるようになります。

タスクリストとして使うと進捗を把握できるので便利。

**Comment by kagekiyo7** [comment]
ありがとうございます！お手すきの際に確認お願い致します。

早速チェックボックス化してみました。他のissuesにも使用してみます。

**Comment by kagekiyo7** [comment]
kitsuki00さんありがとうございます。(wikiは権限がなくても編集するようにすることは可能なのでしょうか)
要望フォームですが、計算機によって対応状況が違うので今後は計算機ごとに変えるか使ってる計算機を記入する項目を追加したほうがいいかも。

**Comment by kitsuki00** [comment]
確認した所、権限なしでは編集できないようです。
私も権限付与する権限は持っていないので、別wikiを作るかwiki用git作って共有するでしょうか。
一応、ほしみさんに連絡してみます。

**Comment by gin0606** [comment]
権限付与できますが、どなたに権限渡せば良いです？

**Comment by gin0606** [comment]
@kagekiyo7 に Collaborator の招待送ったのでご確認ください 🙏

**Comment by kagekiyo7** [comment]
@kitsuki00
ありがとうございます。権限を頂けたので取り敢えず編集してみます。

@gin0606
権限感謝です。(当たり前ですが、あまり余計なことはしないようにします)

**Comment by kei-gbf** [comment]
TODOとして利用させてもらいます

#259 サポアビの未実装分メモ (残りHP依存の処理で、背水グラフ等への適用)
- did not implement their supports for haisui Graph
  - Ayer
  - Beatrix (Themed)

**Comment by kei-gbf** [comment]
> 表示する項目の「スキル合計の数値」が上限に達していたら色を付ける(DATAだけ?)

守護を調べてるときに見かけた情報だけど、守護も(方陣だけ？) 枠上限ありましたね。
340% (加護無し or 加護前100%?) かの検証情報は見当たらず。
