### ISSUE TITLE
要望フォームからの要望一覧

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#152]
groovmanさんの元カレ計算機を元に確認しています。

・参照
https://docs.google.com/spreadsheets/d/1zH5OKPLSbFiNhXOjy1GNgqjjHMvDOEwu2Ani1v54nxE/edit#gid=2011749702
(kitsuki00さんありがとうございます！)

- [x] イクサバ4凸の第一スキル「攻刃III」変更

- [x] ヤイア(クリスマスver) サポアビ1対応
>『護るべし、その笑顔』
>ヤイアがメインメンバーにいる場合、自分以外の味方のクリティカル確率UP(倍率20%/発動率約20%)

全体ではなく自分以外なので対応が難しそう

- [x] 更新通知

個人的には規模の大きいサイトを運営していらっしゃるミムメモ速報さんにお願いしたいです。

- [x] アーカーシャ-槍 のスキル2「不壊の誓約」対応
>得意武器が「槍」「刀」のキャラのHPが80%以上の時に与ダメージ上昇(敵最大HPの1%分加算/最大3万)
- [x] 黄龍槍のスキル2「震天の境界へと至りし者」対応
>光属性キャラが弱体効果「奥義封印」無効/奥義ダメージ20%UP/奥義ダメージ上限20%UP ◆メイン装備時

メイン装備時のみなので、武器選択をするときに有効か無効か選べたほうがよさそう。

- [ ] 背水渾身グラフで単攻撃ダメージの平均値を出す
- [ ] パーティ情報とダメージシュミレーターにブレイクアサシンとシヴァのバフの欄を追加
- [ ] 背水渾身グラフの横軸項目「被ダメージ量」追加
>背水渾身グラフの横軸は現在残りHP割合または残りHPとなってますが，そこに被ダメージ量も追加して欲しいです。グラフの形としては現在の残りHPを右揃えにして左右逆転したものになります。
>
>なぜそれを追加して欲しいかといいますと，
>例えば，フィンブルを２本積むか３本積むかということを考える際に現在の計算機ではHPが〇〇%を越えていれば３本積んだ方が良いということがわかります。
>ですが，フィンブルには守護がついているため最大HP量が大きく変わりますので，実際に２つの編成で同じ攻撃を受けた場合，HPの割合に大きく差が出ます。
>よって，被ダメージがいくら以上ならばフィンブルは３本の方が良いといった情報の方がとても有用です。
>また，フィンブルに関してのケースが特に顕著ですが，ほとんどの場合，残りHP割合よりも被ダメージ量の方が判定の基準として有用です。例外は，ゾーイやアイル，火傷等割合でHPが削れることがある場合くらいです。

- [x] 玄武殻拳のスキル1「霧氷の追牙・肆」効果量更新(現在はSlv=追撃%)
https://cdn-ak.f.st-hatena.com/images/fotolife/g/greatsundome/20160926/20160926150926.png

- [ ] 保存タブ：ブラウザに保存されたデータの並び替え

- [ ] 召喚石/キャラタブの詳細にある「削除」は項目を消すのではなくフィールドをリセットするだけなのでわかりやすくするため名前を変更(画像上)
![image](https://user-images.githubusercontent.com/22173829/62314554-45dec200-b4ce-11e9-9a9b-4a59166248e1.png)

- [ ] まとめて比較のグラフから任意のグラフを非表示にする機能
>背水渾身グラフを表示した際に、召喚石、武器セットを複数選択すると、まとめて比較のグラフに召喚石の数＊武器セットの数の線が表示されます。
>しかし、実際に欲しいデータは、ある召喚石での最適武器セットと他の召喚石での最適武器セットの比較である場合が多いと思います。
>(現状では、求めていない召喚石と武器セットの組合せの線も表示されてしまう。）
>つきましては、まとめて比較のグラフから任意のグラフを非表示にする機能を実施していただければと思います。

- [x] 奥義上限枠の見直し
→#155

- [ ] 条件違いのデータ比較をするため、キャラ、武器、全体バフにそれぞれ、「平均に含める含めない」「最大本数0」「効果量0」に一括で変更するON/OFFチェックボックスの設置

使い所あるかな…？

- [ ] Reactのアップデート
https://twitter.com/lovetanpopo/status/1122892877762154497

- [ ] 武器入力をした後から＋を変える機能、さらに一括で＋を変える機能

- [ ] セレストハープ・マグナの5凸のスキル効果量

**Comment by nt-maeda** [comment]
> 更新通知
個人的には規模の大きいサイトを運営していらっしゃるミムメモ速報さんにお願いしたいです。

こちらでも要望頂いてまして、出せる形になるなら是非協力も出せていただきたいのですが、現状では私が引っ張ってきた内容になっちゃいそうで難しいところです…

**Comment by mimumemo** [comment]
> 更新通知
個人的には規模の大きいサイトを運営していらっしゃるミムメモ速報さんにお願いしたいです。

こちらについては出来るなら是非協力させていただきたいのですが、現状、武器データなどについては各自plから引っ張ってくる形の運用になってしまっており、出すにしても私が引っ張ってきた内容準拠になっちゃうのがちょっとむずかしい感じです・・・

**Comment by kagekiyo7** [comment]
@mimumemo 
ご返信ありがとうございます、了解しました。
更新通知といっても元カレ全体のではなく、ミムメモ速報さんの元カレ計算機を更新した際にちょっと呟いていただくだけで十分なので(なんなら更新内容無しで更新したとだけでも)、気が向いたらよろしくおねがいします。

(現在の更新ならこんな感じ)
・虚無武器の実装
・防御デバフ対応
・スキル効果量の修正
・キャラ基礎連撃率の修正
他キャラ、武器更新
(※現在、仕様変更により過去の編成データが読み込めなくなっているので注意)
