### ISSUE TITLE
奥義の仕様見直し

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#155]
task:
- [x] 奥義上限見直し
- [x] 固定ダメージの対応
- [ ] 一部奥義の奥義追加ダメージ(アビリティダメージor奥義割合ダメージor無属性固定ダメージ)対応
- [ ] 武器に奥義倍率の設定を行い、設置した「メイン武器にする」のチェックボックスを押すことで主人公の奥義倍率が変わるようにする
- [x] 「反骨 or 追い打ち or 破壊の導」付与時 +50万対応
- [ ]  奥義減衰と倍率が変わる特殊な奥義の対応(サポアビに入れる?)
ミリン(200％奥義)
サーヴァンツ ドロシー＆クラウディア(連携時)
イングヴェイ(タフガイ)

取り敢えず現状では奥義上限スキルがおかしいと思います。イクシード、通常必殺、方陣必殺を入れた武器を複数を追加したところ奥義ダメージ上限UP合計90%となり上限60％が設定されていないことを確認しました。ついでに折角なので奥義の仕様について調べてまとめてみました。

# 奥義仕様まとめ
## 計算式
>奥義ダメージ ＝
　[与ダメージ]
　　× 奥義倍率
　　× （ 1 ＋ 奥義ダメージUPスキル ）
　　× ｛ 1 ＋ 奥義ダメージUPバフ ＋（ 奥義ダメージUP(累積)バフ × 累積回数 ）｝
　　×　奥義ダメージ上限補正
　　× （ 1 ＋ ダメージ上限UPバフ ＋ 奥義上限UPバフ ）「反骨 or 追い打ち or 破壊の導」付与時 +50万
　　×　( 1 ＋ セラフィック補正 ＋ アーカルム加護(サブ時) )
　　＋ 奥義固定ダメージ　(全ての乗算計算後に加算、例外あり)
http://gbf-wiki.com/index.php?%A5%B7%A5%B9%A5%C6%A5%E0%BB%C5%CD%CD%B4%D8%CF%A2#aaf8f30a

=(通常攻撃ダメージx奥義倍率x奥義UP)x(減衰x奥義上限UP)xセラフィック +(固定ダメージxセラフィック)

一部の奥義ではここにさらにアビリティダメージor奥義割合ダメージor無属性固定ダメージが加算される(現在未対応)
https://docs.google.com/spreadsheets/d/1kea2IL6wLNbw4RNUcrrxMTpoIdlXU13pYOzBXjgoBbs/edit#gid=199555968
与ダメージ上昇効果が付いていたらその分もプラスされる(セラフィック効果が乗る)(奥義のアビダメ追撃があったらそこにも乗る)
https://twitter.com/zekasyuz/status/969385756601892864
https://twitter.com/zekasyuz/status/963059530518036480

以下式中の各用語について説明
## 与ダメージ
通常攻撃で実際に与えるダメージ量のこと

計算式
http://gbf-wiki.com/index.php?%A5%B7%A5%B9%A5%C6%A5%E0%BB%C5%CD%CD%B4%D8%CF%A2#aaf8f30a

## 奥義倍率
キャラ固有、主人公は武器固有

一覧表
https://docs.google.com/spreadsheets/d/1kea2IL6wLNbw4RNUcrrxMTpoIdlXU13pYOzBXjgoBbs/edit#gid=199555968

## 奥義ダメージUPスキル
武器効果での奥義ダメージUP効果は全てこちら

・上限枠について
方陣必殺枠:100%
秘奥枠:100%(予想)
https://twitter.com/zekasyuz/status/994973819910541312

通常必殺枠:100%(予想)
https://twitter.com/Hecate_mk2/status/1029312790542999552
英雄もここ

コスモスAT枠:20％
https://twitter.com/zekasyuz/status/996535965568024576

## 奥義ダメージUPバフ
武器スキル以外の全ての奥義ダメージUP効果はこちら(サポアビやLBも)(ゼノコキュ杖だけは例外でこっち)
https://twitter.com/jpokiehl/status/1110088637025128448
元カレでは召喚石タブの「奥義ダメージ」

## 奥義ダメージ上限補正
減衰補正を掛ける部分。減衰ラインは一部のキャラを除いて共通。

奥義減衰  | 第1減衰 | 第2減衰 | 第3減衰 | 第4減衰
-- | -- | -- | -- | --
減衰ライン | 1,500,000 | 1,700,000 | 1,800,000 | 2,500,000
減衰率 | 60% | 30% | 5% | 1%

減衰の適応手順についてわかりやすく説明
http://greatsundome.hatenablog.com/entry/2015/10/07/114737#%E3%83%80%E3%83%A1%E3%83%BC%E3%82%B8%E4%B8%8A%E9%99%90%E6%B8%9B%E8%A1%B0%E8%A3%9C%E6%AD%A3%E3%81%A3%E3%81%A6%E3%81%AA%E3%82%93%E3%81%9E

一覧表
https://docs.google.com/spreadsheets/d/1kea2IL6wLNbw4RNUcrrxMTpoIdlXU13pYOzBXjgoBbs/edit#gid=199555968

## ダメージ上限UPバフ、奥義上限UPバフ 
カグヤとかレイジIV。各減衰ラインを効果%分引き上げる。
ジータタブの下の方で両方設定可能(但しゲーム内の仕様とは違いダメージ上限アップの方は奥義上限に影響を与えない)

計算式には書いてないがその他奥義上限スキルやサポアビ、LB、マスターボーナス、天司石もここに加算される。
https://twitter.com/usa_akasa/status/1030457248508596229

・奥義上限スキルの枠について
通常必殺枠(上限30%)、方陣必殺枠(上限30%)、イクシード枠(上限30%)があり、その3つの合計は60%上限に制限され、この60%上限に四象邪系枠(上限20%)やオメガ枠(上限15%)等他奥義上限が加算される。
https://twitter.com/Hecate_mk2/status/1035421551628148736
https://twitter.com/Hecate_mk2/status/1035406237930684416

通常必殺枠は英雄も含まれる

その他奥義上限スキル一覧表
https://twitter.com/Hecate_mk2/status/1062146074549207041

## 「反骨 or 追い打ち or 破壊の導」付与時 +50万
現在未対応。破壊の導はシヴァ召喚効果。
各減衰ラインに50万加算

## 奥義固定ダメージ
キャラ固有、主人公は武器固有

一覧
https://docs.google.com/spreadsheets/d/1kea2IL6wLNbw4RNUcrrxMTpoIdlXU13pYOzBXjgoBbs/edit#gid=199555968

セラフィック効果やクリティカルの影響を受ける
https://twitter.com/zekasyuz/status/963059530518036480

現在未対応?

**Comment by kei-gbf** [comment]
> 奥義ダメージ上限UP合計90%となり上限60％が設定されていない

計算式の全容を把握してませんが、部分的なレスになります。
武器枠の3種のみ（オメガ枠除く）なら以下のような感じでどうでしょう。
草案として出しておきます。(PRも送られてるようなので、可能ならPRお願いします)

ファイル src/global_logic.js calcBasedOneSummon関数内 (500行目付近)
```diff
-       var ougiDamageLimit = buff["ougiDamageLimit"] + totals[key]["ougiDamageLimitBuff"] + ougiDamageLimitByMagna + ougiDamageLimitByNormal + ougiDamageLimitByExceed
+       var ougiDamageLimit = (buff["ougiDamageLimit"] + totals[key]["ougiDamageLimitBuff"] +
+                              Math.min(60, ougiDamageLimitByMagna + ougiDamageLimitByNormal + ougiDamageLimitByExceed));
```

各項は、以下の通りです。
自分の把握してないのは、バフにも上限設定があるのかどうかと、
上限60%の枠にバフが含まれるのか、辺り。

- [x] buff["ougiDamageLimit"]
  - [x] オメガの「通常上限」「奥義上限」キーの影響を確認
  - [x] スキル:舞姫の演武
- [ ] totals[key]["ougiDamageLimitBuff"] キャラ毎の個別バフ？
- [x] ougiDamageLimitByMagna 方陣武器スキル枠
- [x] ougiDamageLimitByNormal 通常武器スキル枠
- [x] ougiDamageLimitByExceed EXceed武器スキル枠

**Comment by kagekiyo7** [comment]
ありがとうございます！
試してみましたが、奥義上限が枠それぞれ60%となり僕の思っていた挙動とは異なりました。

上限60%というのは、通常必殺枠(上限30%)、方陣必殺枠(上限30%)、イクシード枠(上限30%)があり、その合計が60%上限に制限されるという意味です。
この60%上限に四象邪系枠(上限20%)やオメガ15%、バフ、LB、サポアビ等の他奥義上限が加算されます。

バフ上限は恐らくないと思います。(今の所聞いたことがない)

**Comment by kei-gbf** [comment]
- [ ] オメガや四象邪系の枠上限が20%
   この上限チェックは元彼コード内では未確認

buff["ougiDamageLimit"] と totals[key]["ougiDamageLimit"] を読み違えてた部分がありました。
上の各項の～は誤りみたいなので、一時撤回します。

後、"60" と固定値で書いてしまった部分も、0.6 なのか 60 なのかも調べずに書いてしまいました。

コードを追ってくとオメガとイクシードが同枠の変数に入れられてそうな気がする。。
もう少し調べ直してからブランチ作ってみますね。

**Comment by kei-gbf** [comment]
ブランチ作りました b014f0a1f3cf121098af97f552b2ec1c474f482a

スミマセン、数値ですが "60" ではなく 0.60  でした。
（個別の枠上限は直前で計算されており、表記が 0.30 だったので、桁数を揃えてます）

Math.min(0.60, 方陣+通常+EX) で、Math.minは小さい方の値を返す関数なので、
3つの合計の上限が60%になるはずなのですが、枠自体の見直しが必要なのかもしれないです。

気になったのが、オメガや四象邪道等の上限アップがイクシードと同じ枠、
src/global_logic.js 内では `totals[key]["ougiDamageLimit"]` に入れられている点。
※コードを読んだだけの感想なので計算機上では未検証です。

**Comment by kei-gbf** [comment]
あー。今、元コードの意図把握しました。

(恐らく石加護が載らないから)プログラム内ではイクシードとオメガを同枠で計算してたけど、
他枠と合算の上限をチェックするとなると、イクシードを別枠で計算しないといけない。

なので、上記の合算の枠上限60%チェックだけでは不十分で、
武器スキル計算時にイクシードを別枠で扱うような変更が必要そうです。


もし細かい計算等の検証可能であれば試して貰いたいのですが、
現状の元彼計算機だと、イクシード＋邪道系＋オメガが同枠上限30%で計算されてます？

**Comment by kagekiyo7** [comment]
ブランチの方試してみました。上限60%確認できました！
(Groovmanさんのをコピーしたブランチにマージしようとしたら競合してできなかったけど大丈夫なのかな？)

----
ミムメモさんの元カレでイクシード＋邪道系(通常上限7%という名前になっていますが)＋オメガでの上限30%を確認しました。
https://i.imgur.com/VvqxSFI.png
なるほど、色々こんがらがった状態になっているんですね…

奥義上限UP10%というどの武器にも設定されていないスキルがあるけどこれはなんだろう。

**Comment by kei-gbf** [comment]
f9bc07ce486e148894b978afb74e098eb50f726f 以下のように変更しました。

- [ ] buff["ougiDamageLimit"] ？
- [ ] totals[key]["ougiDamageLimitBuff"] キャラ毎の個別バフ？
- [x] 合計の枠上限60%
  - [x] ougiDamageLimitByMagna 方陣枠 (枠上限30%)
  - [x] ougiDamageLimitByNormal 通常枠 (枠上限30%)
  - [x] ougiDamageLimitByExceed Exceed枠 (枠上限30%)
- [x] オメガの「奥義上限」(枠上限15%)
- [x] totals[key]["ougiDamageLimit"] (枠上限20%)
  - [ ] スキル:舞姫の演武
  - [ ] 四象武器スキルの邪系

チェックが枠上限のある箇所。
以下にコード抜粋します。Math.min が上限チェック。

```javascript
var ougiDamageLimitByExceed = Math.min(0.30, totals[key]["exceedOugiDamageLimit"]);
var ougiDamageLimitByNormal = Math.min(0.30, totals[key]["normalOugiDamageLimit"] * totalSummon["zeus"]);
var ougiDamageLimitByMagna = Math.min(0.30, totals[key]["magnaOugiDamageLimit"] * totalSummon["magna"]);
var ougiDamageLimit = Math.min(0.20, totals[key]["ougiDamageLimit"]);
ougiDamageLimit += Math.min(0.15, totals[key]["omegaOugiDamageLimit"]);
ougiDamageLimit += Math.min(0.60, (ougiDamageLimitByMagna + ougiDamageLimitByNormal + ougiDamageLimitByExceed));
ougiDamageLimit += buff["ougiDamageLimit"] + totals[key]["ougiDamageLimitBuff"];
```

プログラム内部の変更:
イクシードとオメガ等が同枠で計算されていたのを、枠上限をチェックする為、個別に分離。
オメガや四象邪系がイクシードの枠上限にかかっていたのを解消。

競合については、Groovmanさん側の変更は、計算式やコードを読みやすく変えたのみ。
機能に影響はないので、競合箇所を編集し解消するだけで大丈夫です。

----

> 奥義上限UP10%というどの武器にも設定されていないスキルがあるけどこれはなんだろう。

調べてみたところ、リミットブレイク（イクシードの旧名称）で使われていたようです。

Github内でコードを閲覧すると「Blame」から過去のコミットを辿れます。
行番号左のアイコンより辿った履歴

- d6fc6299d991ed02075ae9934873f563a550a023
- #56

スキル自体を削除してしまうと、古い編成データ読み込みで問題になりそうなので、
互換性維持の為に残しているのだと思います。

**Comment by kagekiyo7** [comment]
スキル:舞姫の演武は四象邪系なんですかね？どちらにせよ水で20%に届くことはないので問題がなさそうです。
https://twitter.com/firemagma/status/869206818676908032

上昇系スキルの一覧表があったので貼っておきます
https://twitter.com/Hecate_mk2/status/1062146074549207041

黄龍槍は現在未対応、麒麟弓は四象邪系と同じスキル:通常上限10%で設定されているので新たに枠を設ける必要がありそうです。

**Comment by kei-gbf** [comment]
一覧表ありがとうございます
一番上のコメントにも追記していただけると、資料として使えるので助かります。

スキル:舞姫の演武について、ゲーム内追検証は…手持ち無いので出来ない。

計算機内コードでは四象邪系と同枠で加算されていました。
同枠というか、通常・方陣・その他石加護の載らないものという３つの分類でした。

> どちらにせよ水で20%に届くことはないので問題がなさそうです。

緋舞扇複数本なの場合ってゲーム内ではどうなるんでしょう？
現状の計算機だと累算されてそう。（未テスト）


過去のコミットを見て思ったのですが、コミット時に関連する issue 等の番号をかいて
そちらに検証元情報のリンク等を貼っておくと良さそうですね。
（後から、コードから履歴を辿り、実装時の情報が追いやすくなる）

----

> 現在、ガフスキー及びペンデュラムの奥義上限はスキル側の仕様で何本入れても15.0%になるように> なっているみたいなので枠として設定する必要はないかも(?)

これは確かに、その通りです。

現状ではどちらも同じ計算結果になるはずですが、厳密には違いがあり
（ペンデュラムまだ詳しく調べてないので間違ってるかもしれませんが、オメガ15/終末15と仮定として）

- オメガ15 + 終末15 = 30 枠上限適応で 15%
- オメガ15 + 終末15 重複しないので 15%
 
後者の場合、同枠で効果量の高いスキルが出てきた場合に、枠上限が違ってくる可能性が残ってます。

但し、プログラム側の都合になるのですが、ペンデュラムの実装次第では、
スキルの重複チェックをオメガと終末の両方で行うよりも、
前者のように、一旦同枠で加算して上限を適応する方がシンプルな処理になるので、
上限と重複チェックの厳密な区別が必要になった時に変更でも良いと思ってます。（問題先送り）

----

黄龍槍は…、メイン武器の扱いって元彼計算機ではどうしてるんでしょう？
キャラの個別バフで対応できるのかな。。

現状で、黄龍槍メイン装備を計算する場合は、
このジータタブの奥義を使うことになるんでしょうか。

この辺は、私はまだ把握してない部分が多い。
黄龍槍は別にして、合算枠上限60%のブランチで一旦PR投げてみます。

**Comment by kagekiyo7** [comment]
>一覧表ありがとうございます
>一番上のコメントにも追記していただけると、資料として使えるので助かります。`

追加しておきました。

>緋舞扇複数本の場合ってゲーム内ではどうなるんでしょう？

おっとそうでしたね、四象邪系と違い複数作れるんでした。ニッチすぎて検証はされていないみたいですね…。まあ取り敢えず四象邪系と同じ枠でいいのではないしょうか。

>過去のコミットを見て思ったのですが、コミット時に関連する issue 等の番号をかいて
>そちらに検証元情報のリンク等を貼っておくと良さそうですね。

それは確かにそうですがPRを送る人がissuesにも情報をまとめないといけなくなるので負担が増えてしまうかも? 取り敢えず僕はやってみることにしますね。

>後者の場合、同枠で効果量の高いスキルが出てきた場合に、枠上限が違ってくる可能性が残ってます。

確かに、現状だとゲーム内で1本しか有効にならないようになっているのか、枠として設定してあるのかがまだ判断できないので両方設定しておいて損はないですね。

>メイン武器の扱いって元彼計算機ではどうしてるんでしょう？

現状、ブリューナク(貫きの牙)のみがメイン持ち時のスキルが追加されていて手動で切り替えができる形ですね。僕としては、メイン持ち時のスキルはオメガ武器のように追加時に選択できるようにするのがいいかなと思います。

もしくは武器詳細にこんな感じのスペースを作るとか
![image](https://user-images.githubusercontent.com/22173829/56740681-5cc59800-67ac-11e9-8a87-78f425e44fbe.png)

**Comment by kei-gbf** [comment]
>> 過去のコミットを見て思ったのですが、コミット時に関連する issue 等の番号をかいて
>> そちらに検証元情報のリンク等を貼っておくと良さそうですね。

> それは確かにそうですがPRを送る人がissuesにも情報をまとめないといけなくなるので負担が増えてしまうかも? 取り敢えず僕はやってみることにしますね。

Issue が既にある場合のみでいいのでお願いします。
（Issue番号をコミット文やPRのメッセージに含めるだけで済みます)
Issue がない場合は、(わざわざIssue作らなくても)PRのレビューでコメント内で良いと思います。

----

メイン武器の情報ありがとうございます！早速、調べてみます。

**Comment by kagekiyo7** [comment]
先日マージされたPRですが、バグがあるようです…
条件：バフ、武器無し
![image](https://user-images.githubusercontent.com/22173829/56822351-bbae0e80-688b-11e9-8017-521d0ef51f04.png)

**Comment by kei-gbf** [comment]
@kagekiyo7 
どのPRでしょう？再現手順教えてもらえますか？

**Comment by kagekiyo7** [comment]
#157 こちらですね。

発生が確認できたリポジトリはこちら。
https://github.com/kagekiyo7/motocal/commits/master

groovmanさんの計算機でも確認することができます。まっさらな状態でキャラを追加すると発生します。
https://motocal-groovman.netlify.com/

**Comment by Groovman** [comment]
I think I can guess where the error is. Give me some time.

**Comment by kei-gbf** [comment]
確認できました。

内部の計算で新規に追加した、オメガ枠とイクシード枠の初期化で
主人公とキャラが別々になっていて、主人公しか初期化処理ができていなかったようです。

**Comment by kei-gbf** [comment]
@Groovman 

Thank you, I made PR just now
