### ISSUE TITLE
アーカルム石サブ加護対応

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#158]
作ってみました。動作確認まで済んでいます。
プログラミングの知識が大してないまま書いたのでよろしければいい部分だけコピー＆修正してPR作成お願いします🙇
https://github.com/kagekiyo7/motocal/commits/kagekiyo7-patch-test
(上から7つ目まで)

現在の仕様だとサポアビと効果が重複するが、ゲーム中だとどうなんだろう…
天司武器とサポアビだと高いほうが優先されるけど

懸念点
名前は与ダメージ加護のほうがいい(？)
マウスオーバー時の説明が出てこない

メモ：
charaUniqueDamageUP サポアビ用に作成された変数

**Comment by kei-gbf** [comment]
@kagekiyo7 

コミットを纏めてPR作成できるかなと試してみたんですけど、
ブランチの派生元がGroovmanさんのレポジトリになってるようです。

MotocalDevelopers/motocal への PR を作成するには、競合を解消する必要があるのですが…
この競合解消作業は、#132 と被りそうなので。132がマージされた後にするか、
もしくは、GroovmanさんのレポジトリにPRを送り、取り込んで貰うのが良さそう。

----

> 名前は与ダメージ加護のほうがいい(？)

そうですね。アーカルム石にはHPや防御UPもあるのと、召喚石では
天司石（ダメージ上限）とアーカルム石（予ダメージ等）の区別もあります。

> マウスオーバー時の説明が出てこない

PR送ります。

**Comment by Groovman** [comment]
Merged it already :)

**Comment by kagekiyo7** [comment]
@kei-gbf 
ありがとうございます！
おっと、Groovmanさんがマージをしたようなので新しくPRお願いできますか？

@Groovman 
Thank you!

**Comment by kei-gbf** [comment]
@Groovman 

I made a popup patch for kagekiyo7/kagekiyo7-patch-test
Can you pick kei-gbf/test-kagekiyo7-patch e137906fd76e9d1b18b39669ca5da03c4a36651d

**Comment by Groovman** [comment]
Could someone kindly press the approve button :)

**Comment by kagekiyo7** [comment]
OKです。名前変更は僕がPR作成しておきます。
