### ISSUE TITLE
マグナ技巧のスキル計算時にホワイトアウト

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#162]
以下の編成でニーベルン・ホルン(4凸)を追加しようとしたらホワイトアウトしました。
(Groovmanさんの計算機で発生。ミムメモさんの計算機では発生しなかったので昨日辺りの更新が原因だと思います)
https://www.axfc.net/u/3975177

他の武器だと追加できますし、まっさらな状態だとニーベルン・ホルンでも追加できるので詳しい発生条件は分かりませんでした。

If you add [4凸]Nibelung Horn in the above party data, it will be white out.

**Comment by kei-gbf** [comment]
cafb2c70f40780bec0986e373d071a254df5fdca で方陣渾身(magnaCritical)の内部実装が変更？

まっさらな状態だと起こらないのは、
属性が一致しないキャラだと武器スキルが計算されない為だと思います。

方陣技巧と通常技巧のテーブルを一纏めにしたみたいなのだけど、
恐らく他の方陣技巧武器でも問題有。方陣刹那は対応済なので大丈夫そうです。

@Groovman 
Error was on this line: src/global_logic.js "else" case of "stype". 
skillAmounts["magnaCritical"]["L"] but no "magnaCritical" key founds in skillAmounts table.

```jsx
} else {
    totals[key][stype] += comb[i] * skillAmounts[stype][amount][slv - 1];
}
```

- left "stype" is "magnaCritical"
- but right stype, that implementation expects skillAmounts["critical"]

that stype == 'magnaCritical' was an implicit case, let make it explicit. (code below not tested)

```jsx
} else if (stype == 'magnaCritical') {
    totals[key][stype] += comb[i] * skillAmounts['critical'][amount][slv - 1];
} else {
```

**Comment by kei-gbf** [comment]
急いで書いた為、いろいろと説明不足でした。

上記コミットで、スキルの効果量が定数だったり効果量が同じで、
個別の配列にする必要がなかったものが取り除かれれました。

マグナ技巧は元々、明示的に対応するコードはなく、if 文の else ～で一纏めに処理されていたのが
今回の skillAmounts の変更により対応できなくなりエラーとなったようです。
影響範囲は、skillAmounts で取り除かれた値を持つ武器スキル全般。

- シエテ、ラストストームハープの組み合わせでもエラーを確認。
- 通常技巧は大丈夫そう。

----

これは、計算機内部でスキル効果量を参照する際の実装方法を変更したのみで、
編成データに保存されるスキルID等の互換性への影響はありません。

**Comment by kei-gbf** [comment]
上記修正内容でPR作ります。

@kagekiyo7 
Issue のタイトルですが、
JavaScriptエラーが出るケースでは大抵同じ症状になる為、変更お願いします。

提案:「マグナ技巧のスキル計算時にホワイトアウト」

勿論、エラーが出た時点では原因はわからないので、
取り敢えずIssue立てて後から変更で良いです。（後々の検索性の為）

**Comment by kagekiyo7** [comment]
@kei-gbf 
変更しました。
