### ISSUE TITLE
スマホ版レイアウト

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#183]
元カレの右側にはスクロールバーが２つあり、一番下にスクロールすると余白が生まれてしまうのですがこれは削除可能でしょうか？
![image](https://user-images.githubusercontent.com/22173829/57351480-f6be1500-719c-11e9-9013-d88bf73aeb03.png)

スマホレイアウトにもあります。
![image](https://user-images.githubusercontent.com/22173829/57351690-ccb92280-719d-11e9-9e98-98c6be0d2ba5.png)

**Comment by kei-gbf** [comment]
![adjust-height](https://user-images.githubusercontent.com/45387555/57422527-68ed3300-724b-11e9-9867-9695b6963c26.PNG)

こんな感じでしょうか。ソースの該当箇所はまだ見つけてませんが
変更してみたのは一か所のみ .main-content の height プロパティ 89% -> 72% 

タイトルのレイアウトは、ラベルで "UI" とか作ると良いかも

**Comment by kagekiyo7** [comment]
ありがとうございます。PR送りました。

スマホレイアウトのは広告用かもしれないので放置

**Comment by kagekiyo7** [comment]
バーナータイプではなく正方形の広告が出てる時にレイアウトが崩壊してしまうのもいつか解決したいところ
![image](https://user-images.githubusercontent.com/22173829/57523317-9fb46d80-735f-11e9-8ba0-621ceca33a54.png)
