### ISSUE TITLE
スキルが反映されない不具合

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#188]
最新のmasterで武器スキルが適応されていない不具合が発生しています
原因は恐らく#170 です(このブランチでの不具合発生を確認しました)。
テスト甘くてすみませんでした…。

**Comment by kei-gbf** [comment]
どのスキルで発生します？再現方法あればお願いします。
#170はセーブデータの対応でしたが、適応されないのは新規の場合でしょうか？

**Comment by kei-gbf** [comment]
テストは、マージ前に 自動でチェックが出来るのですが、(.travis.yaml)
ライブラリ等の環境構築のチェックくらいで、
スキルの適応までには及んでないのが現状です。

変更点のテストはPR時に確認できても、
今まで動いてたコードへの影響は、手作業では確認が困難な部分なので、
ここは、テスト自動化するしか無いですね。

人手でやる場合は、どんなテストをするかチェックリスト共有が必要
だけど、PR毎に毎回手作業でやるのはちょっと労力が現実的でないです。

**Comment by kei-gbf** [comment]
全部のスキルで発生。
武器欄へは表示されてるけど、効果が結果へ反映されてないってことかな？

**Comment by kagekiyo7** [comment]
恐らくそうですね。ステータスも一切変動していません
コードの整理時におかしくしまったのではないかと思います

**Comment by kei-gbf** [comment]
初期ミスだったのでリベースしてしまった。
後者のみ有効です ~~05f78dd~~  880d303

**Comment by kei-gbf** [comment]
#189 閉じたけど、マージせずに終了すると自動では閉じられないのですね。

#190 で修正済。I close this issue, fixed in #190
