### ISSUE TITLE
現global_logicからhuanglongHissatsuの処理の項が消えた

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#194]
https://github.com/MotocalDevelopers/motocal/commit/8e3267aa5dbfe1371250be61526a31733019b38a#diff-b64a138ffc2095aa899c65675d80983f

原因はわかりませんが報告だけ

**Comment by kei-gbf** [comment]
masterとの差分で該当箇所のコードが確認できず。
マージの時に入ってなかったので、直前のコンフリクト解消で抜け落ちたっぽいです。
