### ISSUE TITLE
キャラ追加要望

### ISSUE THREAD

**Issue by hsimyu** [MotocalDevelopers/motocal#29]
テンプレートに不足しているキャラがいたら教えてください。

**Comment by hoshimi** [comment]
aaa

**Comment by hoshimi** [comment]
json stringify

**Comment by hoshimi** [comment]
投稿者: おれだ種別: キャラ
キャラ名: テスト
メッセージ:コメントです

**Comment by hoshimi** [comment]
投稿者: ふ種別: キャラ
キャラ名: ひゃー
メッセージ:ほー

**Comment by hoshimi** [comment]
投稿者: おー種別: キャラ
キャラ名: うー
メッセージ:わー

**Comment by hoshimi** [comment]
投稿者: あああ
種別: キャラ
キャラ名: キャラりえ嘘
メッセージ:てｓつお

**Comment by hoshimi** [comment]
投稿者: がｇっｈ
種別: 武器
武器名: ぶきりすとえｔ
メッセージ:が

**Comment by hoshimi** [comment]
投稿者: テスっと
種別: キャラ
キャラ名: あああ
メッセージ:テスト

**Comment by hoshimi** [comment]
投稿者: みやこ
種別: キャラ
キャラ名: ベアトリクス(ハロウィンver)
メッセージ:レアリティ: SR
属性: 火
種族: ヒューマン
タイプ: 特殊
得意武器: 剣
得意武器2: なし
ATK: 6580
HP: 1120
基礎DA率: 6%
基礎TA率: 3%
奥義倍率: 3.5倍
サポアビでHP依存のクリティカル確率UP（倍率50%）

※DA/TA率と奥義倍率はすんどめ侍様の検証より
http://greatsundome.hatenablog.com/entry/2016/10/27/001753

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルシオ
メッセージ:ルシオ追加希望です！

**Comment by hoshimi** [comment]
投稿者: まる
種別: キャラ
キャラ名: ルシオ
メッセージ:ルシオ追加希望です！

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルシオ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルシオ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 要望テスト
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ゾーイ
メッセージ:もっとらん奴おりゃんやろ？ｗ

**Comment by motocal-request** [comment]
投稿者: ＠い
種別: キャラ
キャラ名: ロザミア
メッセージ:SSRの追加お願いします。

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ラスティナ
メッセージ:くっころドラフ

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ベアトリクス(水着ver)
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ベアトリクス(水着ver)
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ベアトリクス(水着ver)
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 水着ベアトリクス
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: アニラ（SSR）
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: パーシヴァル
メッセージ:レベル100の攻撃力とHPになっていない

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: アニラ（ＳＳＲ）
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ルナ
メッセージ:フェリ生贄TAコンボ要員として

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: アニラ（SSR)
メッセージ:加えてください

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ゼタ(闇)
メッセージ:お願いします

**Comment by motocal-request** [comment]
投稿者: ふぁーる
種別: キャラ
キャラ名: アニラ
メッセージ:SSRのアニラがいないような気がします。
お願いします。

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: アニラ
メッセージ:SSRの方

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 알타
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: オーキス
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルリア
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: レ・フィーエ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: スツルム // Sturm
メッセージ:https://gbf.wiki/Sturm_(Grand)

**Comment by hoshimi** [comment]
投稿者: えりゅしおん
種別: キャラ
キャラ名: 奥義ゲージ上昇量にマイナス値
メッセージ:コールオブアビスなどで奥義ゲージ上昇がマイナスとなるように設定して計算することは可能でしょうか？

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルリア
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルリア
メッセージ:

**Comment by hoshimi** [comment]
投稿者: ゆばば
種別: キャラ
キャラ名: 闇カリオストロ
メッセージ:んほぉ！いぐぅ！

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: 闇カタリナ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ソシエ 火属性バージョンについて
メッセージ:このキャラは現在得意武器 なしになっていますが
得意武器 格闘です。
ほぼ同ステの武器を入れ替えて確認しました。
よろしくおねがいします。

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Dark Katalina
メッセージ:Please add Dark Katalina

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ドランク(リミテッドver)
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Cagliostro (Dark)
メッセージ:Dark version of Cagliostro.

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Katalina (BD)
メッセージ:アニメBDのカタリナさんお願いします！

**Comment by hoshimi** [comment]
投稿者: ルキ
種別: キャラ
キャラ名: カリオストロ（新バージョン）
メッセージ:イベント「アストレイ・アルケミスト」で追加されたキャラが追加されていないため、追加を希望します

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: 闇カタリナ
メッセージ:追加よろしくお願いいたします

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: カタリナ（闇）
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: カリオストロ
メッセージ:ハロヴィンだけなので、恒常verおねがいします

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ヴェイン
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: カタリナ
メッセージ:DVD特典の闇属性カタリナをおねがいします

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ドランク
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Katalina SSR Dark
メッセージ:promo from animation disc purchase is missing

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: ドランク (Drang)
メッセージ:http://gbf-wiki.com/index.php?%A5%C9%A5%E9%A5%F3%A5%AF+%28SSR%29

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: スカーサハ
メッセージ:EN 
Scathacha

**Comment by hoshimi** [comment]
投稿者: ふゆうさぎ
種別: キャラ
キャラ名: ルリア
メッセージ:属性　主人公と同じになる
種族　人間　
特殊タイプ
通常攻撃なし　
アビリティーを使うごとに奥義ゲージ30％UP
HP　　　640
攻撃力　4400

**Comment by hoshimi** [comment]
投稿者: トイトイ
種別: キャラ
キャラ名: タイアー
メッセージ:風SR　アタッカー。ティア銃では編成しやすいキャラですので是非

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: スカーサハ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: スカーサハ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 十六夜りくろ
種別: キャラ
キャラ名: スカーサハ
メッセージ:単純に表示されないので、よろしくお願いします

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: アルベール
メッセージ:ＳＲ（イベント）のアルベール

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: スカーサハ
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ルリア
メッセージ:イベント限定キャラ

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Scathacha
メッセージ:

**Comment by hoshimi** [comment]
投稿者: yuki
種別: キャラ
キャラ名: タイアー
メッセージ:レア度：SR
属性：風
種族：ヒューマン
タイプ：特殊
MAX Lv：70
MAX HP：1050
MAX ATK：6730

よろしくお願いいたします(*´∀`)ﾉ

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: 狐狸
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:2017年６月にプレイアブル化したユグドラシルの追加を希望致します。

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:ゆぐゆぐがいない。。。？

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:６月レジェフェスから追加されたユグドラシルの追加をお願いします

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:

**Comment by hoshimi** [comment]
投稿者: shu
種別: キャラ
キャラ名: ユグドラシル
メッセージ:土
星晶獣
特殊
格闘
攻撃6800
HP1900

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:星晶獣

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:土属性　星晶獣

**Comment by hoshimi** [comment]
投稿者: 土パ好き
種別: キャラ
キャラ名: ユグドラシル
メッセージ:特殊タイプ
土
星晶獣

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: ygg
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: earth
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: J・J水着ver
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: キャラ
キャラ名: キャラテンプレート
メッセージ:キャラテンプレートを選択して、消そうとすると消えません。不具合なんでしょうか？確認お願いします

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: dark
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: l
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: l
メッセージ:

**Comment by hoshimi** [comment]
投稿者: 
種別: Chara
Chara名: Herja
メッセージ:SR

**Comment by hsimyu** [comment]
投稿者: 
種別: Chara
Chara名: Izmir (Summer)
メッセージ:https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/64003

サポアビ【真夏の夜の夢】効果

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ソーン
メッセージ:最終解放時、Ｌｖ．100の時のステータスと魔眼の狩人の補正

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユグドラシル
メッセージ:種族不明ではなく星晶獣でお願いします

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ジャミル（闇）
メッセージ:

**Comment by hsimyu** [comment]
投稿者: はる
種別: キャラ
キャラ名: 水着イシュミール
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アイル
メッセージ:水着アイルお願いします

**Comment by hsimyu** [comment]
投稿者: お世話になっております
種別: キャラ
キャラ名: ルナール
メッセージ:ファクシミリ

属性|闇
ATK|4600
HP|550
タイプ|特殊
得意武器|杖
種族|ハーヴィン

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アルタイル
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: エッセル
メッセージ:最終開放をいれてほしいです

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: グレア
メッセージ:SSR,SR共に追加してほしいです

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: グレア
メッセージ:お願いします

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ヴェリトール（SR）
メッセージ:得意武器：剣
バランスタイプ

**Comment by hsimyu** [comment]
投稿者: Valuno
種別: Chara
Chara名: Anne
メッセージ:She isn't in the template database

**Comment by hsimyu** [comment]
投稿者: Valuno
種別: Chara
Chara名: Anne
メッセージ:She isn't in the template database

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: カイラナ
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アン
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 有琉　部伊瑠
種別: キャラ
キャラ名: アルベール
メッセージ:アルベールが足りていません。
補充をお願いします。
あああああああるべえええええええる宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇宇ううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううううって感じです。

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アン
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ゾーイ
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アザゼル
メッセージ:

**Comment by hsimyu** [comment]
投稿者: Shimat
種別: Chara
Chara名: アザゼル / Azazel
メッセージ:http://gbf-wiki.com/index.php?%A5%A2%A5%B6%A5%BC%A5%EB+%28SSR%29

https://gbf.wiki/Azazel

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユエル
メッセージ:この間実装された水属性のユエルおなしゃす

**Comment by hsimyu** [comment]
投稿者: 
種別: Chara
Chara名: Owen
メッセージ:SR chara came out with Anne

**Comment by hsimyu** [comment]
投稿者: かぼちゃ
種別: キャラ
キャラ名: ユエル(水属性)
メッセージ:レア度：SSR
属性：水
種族：エルーン
タイプ：特殊
得意武器：剣・刀
ステータス上限値
　攻撃：8500
　HP：1140
サポート
　狐火状態の敵に対して味方全体に水属性追撃効果(1割)

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユエル水
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: 水ユエル
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: アザゼル
メッセージ:闇属性
ATK 9990
HP   1380
得意武器 短剣 格闘
攻撃タイプ
魔晶獣(不明)

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユエル(水)
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: オーウエン
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユエル
メッセージ:水

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ユエル
メッセージ:水

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: 水ユエル
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: Chara
Chara名: Grea (SR)
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ルナール
メッセージ:ルナールグラゼロのHP計算で使いたい

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: ジュリエット
メッセージ:得意武器が杖になっている　実際は槍

**Comment by hsimyu** [comment]
投稿者: 
種別: Chara
Chara名: Anne
メッセージ:Anne from mysteria https://gbf.wiki/Anne

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: カルテイラ
メッセージ:風

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: セロニム
メッセージ:風

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by hsimyu** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ランスロット(風属性)
メッセージ:ランスロット風属性版

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ミカサ
メッセージ:イベント追加キャラ

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 風ランスロット
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: あ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: リミヴィーラ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ミリン
メッセージ:ＳＲ　[サムライドリーマー]ミリン

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: マリー（クリスマス版）
メッセージ:レアリティ：SSR
属性：光
種族：ヒューマン
タイスープ：バランス
得意武器：銃
得意武器2：なし
ATK：7900
HP：1630

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ヴィーラ(リミテッドver) (SSR)
メッセージ:【種族】星晶獣　
【タイプ】防御
【得意武器】斧

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ソーン
メッセージ:最終解放後のステータス

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ソーン
メッセージ:最終解放後のステータス

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ヴィーラ(リミテッドver)
メッセージ:レア：SSR
属性:光
種族：星晶獣
タイプ：防御
武器:斧
最大ATK:7200
最大HP:1950

**Comment by motocal-request** [comment]
投稿者: なつめ
種別: キャラ
キャラ名: マリー(クリスマス.ver)
メッセージ:HP 1630
攻撃力 7900
得意武器 銃
ヒューマン バランスタイプ

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: リヴァイ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: アルタイル
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ウーノ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ウーノ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: カトル
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: イルザ
メッセージ:属性　　　　　　　土
種族　　　　　　　エルーン
タイプ　　　　　　攻撃
得意武器1　　　銃
得意武器2　　　弓
素の攻撃　　　　8500
素のＨＰ　　　　1200

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: フレッセル
メッセージ:アルバハやソロチャレでの出番がそこそこあるため

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: f
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: a
メッセージ:

**Comment by motocal-request** [comment]
投稿者: Hyou
種別: キャラ
キャラ名: 土
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: カタリナ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: フミ
種別: キャラ
キャラ名: SSRゾーイ
メッセージ:銃

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: テレーズ(SSR)
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ＳＳＲテレーズ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: Sandalphone
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: サンダルフォン
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: テレーズSSR
メッセージ:

**Comment by motocal-request** [comment]
投稿者: ぽぷ子
種別: キャラ
キャラ名: マルキアレス
メッセージ:ニッチだと思うので、お暇なときに気が向いたらお願いします

**Comment by motocal-request** [comment]
投稿者: ぽぷ子
種別: キャラ
キャラ名: マルキアレス
メッセージ:すいません、、ありました（謝

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ［覚醒の調停者］ゾーイ
メッセージ:Lv80　HP1460・攻撃力8700　得意武器銃
光　星晶獣　バランス

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: サンダルフォン
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: サンダルフォン
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: Jeanne D'arc (Themed)
メッセージ:New swimsuit character - Jeanne D'arc (Themed) (Wind element)

**Comment by motocal-request** [comment]
投稿者: CL
種別: Chara
Chara名: Seruel
メッセージ:er, i ask this template coz i cant find the 5* seruel ver in the chara template, if u could add him it would be great.

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 水着ジャンヌ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 水着ジャンヌダルク
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 水着ジャンヌ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 水着ジャンヌ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: サラーサの得意武器について
メッセージ:解放前サラーサの得意武器がデフォルトで斧のみになっていますが、斧と剣に

解放後サラーサの得意武器がデフォルトで剣のみになっていますが、斧と剣に

それぞれよろしくお願いします

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: Albert
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: 巫女ゾーイ
メッセージ:

**Comment by motocal-request** [comment]
投稿者: Prometheus
種別: Chara
Chara名: Olivia
メッセージ:Can you add Olivia? <3

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: ブローディア
メッセージ:

**Comment by motocal-request** [comment]
投稿者: 
種別: キャラ
キャラ名: アリーザ
メッセージ:イベント「サウザンド・バウンド」にて加入する水属性キャラについてです。
おそらく既に対応中とは思いますが、何卒宜しくお願い致します。

**Comment by motocal-request** [comment]
投稿者: Tiggy
種別: Chara
Chara名: Soriz (SSR)
メッセージ:https://gbf.wiki/Soriz_(SSR) 

Thank you for doing this amazing tool.

**Comment by motocal-request** [comment]
投稿者: 
種別: Chara
Chara名: c
メッセージ:
