### ISSUE TITLE
Graph for expected turn damage(player only) goes way beyond maximum possible damage cap on enmity

### ISSUE THREAD

**Issue by sonickles9** [MotocalDevelopers/motocal#332]
![image](https://user-images.githubusercontent.com/22542590/62744726-458a7d80-ba1e-11e9-899b-80df00853382.png)
![image](https://user-images.githubusercontent.com/22542590/62744764-78347600-ba1e-11e9-971f-61f7c9a91551.png)

Images are self-explanatory, I believe.

**Comment by kagekiyo7** [comment]
Thank you for the report. I knew the problem.
If this PR is merged, it will be improved.
https://github.com/MotocalDevelopers/motocal/pull/312
