### ISSUE TITLE
Graph damage does not include changed Summon Total ATK etc.

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#333]
To be exact, Graph locks Summon Total ATK Default (9500).
The same applies to other TA etc.

## Example
Summon Total ATK: 95000, Others: Default
![image](https://user-images.githubusercontent.com/22173829/62887500-54539600-bd78-11e9-9d57-64f02c7f9e8f.png)
↓ 41157 is correct damage. 4777 is when it's Summon Total ATK 9500.
![image](https://user-images.githubusercontent.com/22173829/62887423-279f7e80-bd78-11e9-9b2d-726b1dd794eb.png)

For some reason, "Compare All"(まとめて比較) displays correct damage.
![image](https://user-images.githubusercontent.com/22173829/62887446-338b4080-bd78-11e9-8026-e7f6399664a4.png)

And when Summon Element value is changed, the correct damage is displayed. I don't get it.
![image](https://user-images.githubusercontent.com/22173829/62887691-b90ef080-bd78-11e9-80d5-44735901455a.png)

**Comment by kei-gbf** [comment]
## Problem
when summon1 and summon2 were same aura, summon1 is ignored
召喚性セットの1と2が同じ場合、召喚石セット1が個別グラフに表示されない

  (召喚石セット2が表示される為、召喚石セット1の入力値が適応されてないように見える）

## Cause
global_logic.js generateHaisuiData 

```js
    var data = {};

    data["火マグナ100 + 火属性140"] = 召喚石セット1のデータ
    data["火マグナ100 + 火属性140"] = 召喚石セット2のデータ
```
と後ろのデータに上書きされています。

## Solutions
ユーザ側で出来る対応 User side solution:
- change summon1 and summon2 aura different
  石加護を違ったものにすると解消されます

プログラム側で出来る対応 Program side solution
- 結果を格納するデータ構造を変更する。change the dictionary key
  - 通し番号を振り、辞書に格納するキーを変える。like add index number for unique key
