### ISSUE TITLE
Some MC individual buffs only apply for first entry of calculated grids

### ISSUE THREAD

**Issue by sonickles9** [MotocalDevelopers/motocal#400]
CA specs buffs only
![image](https://user-images.githubusercontent.com/22542590/71521621-48d4b780-28a0-11ea-9bc8-918fd3650bee.png)
![image](https://user-images.githubusercontent.com/22542590/71521815-0a8bc800-28a1-11ea-8bb4-eafd34c685b0.png)
![image](https://user-images.githubusercontent.com/22542590/71521830-17102080-28a1-11ea-923d-87ac3aa2accc.png)

CA specs + Boost DMG (one-foe) buffs
![image](https://user-images.githubusercontent.com/22542590/71521638-57bb6a00-28a0-11ea-861a-b4705b4fd14f.png)
![image](https://user-images.githubusercontent.com/22542590/71521755-d2848500-28a0-11ea-94b0-e1b4e826eb98.png)
![image](https://user-images.githubusercontent.com/22542590/71521797-fcd64280-28a0-11ea-95cb-ce44c174cea1.png)

CA specs (DMG/DMG cap) and Boost DMG/Adversity seem to be affected

**Comment by kagekiyo7** [comment]
Thank you for the report.
No this bug in master.
Probably occurs in the motocal(dev) of @Groovman 
![image](https://user-images.githubusercontent.com/22173829/71529149-9c89e400-2926-11ea-96fa-2d74ee3d2652.png)

**Comment by kagekiyo7** [comment]
Cause: https://github.com/MotocalDevelopers/motocal/pull/399
