### ISSUE TITLE
Memory leaking over long-term usage

### ISSUE THREAD

**Issue by sonickles9** [MotocalDevelopers/motocal#404]
![image](https://user-images.githubusercontent.com/22542590/72675740-7f4cbf00-3a67-11ea-9875-bad0ead2878a.png)
@Groovman 's motocal.

Apparently memory leaks whenever an update is done via auto update (default).
Haven't done any localized tests -- I've changed many values from MC buffs to party buffs to chara stats e.g. nearly everything on left pane.

**Comment by kei-gbf** [comment]
@sonickles9 

thx for report, but it not current master's issue
I've also already reported this on #393, and it's not merged yet.

Close this issue and we can move this topic to PR 393

**Comment by sonickles9** [comment]
Okay
