### ISSUE TITLE
キャラLBの上限アップ希望

### ISSUE THREAD

**Issue by kagekiyo7** [MotocalDevelopers/motocal#63]
指輪LBによって、攻撃力(最大3000)、HP(最大1500)、DA(最大15)、TA(最大10)が付与されることからリスト数値の上限アップを希望します。

また、クリティカル確率項目の追加も希望します。

効果量の詳細です。
https://twitter.com/SSumiwatari/status/980000926244073472

**Comment by Groovman** [comment]
Hi,
The bonus from the rings are boost to "素の攻撃力", "素のHP", "基礎DA率", and "基礎TA率", those fields are unlimited, so you can use those. 
The limited fields under "LimitBonus" are for EMP.

**Comment by kagekiyo7** [comment]
That’s true.
Thank you!
