### ISSUE TITLE
TravisCIを使えるようにする

### ISSUE THREAD

**Issue by gin0606** [MotocalDevelopers/motocal#92]
https://travis-ci.org で motocal のCI設定してもらえると嬉しいです 🙏

https://github.com/MotocalDevelopers/motocal/pull/89 であと登録すれば動く状態になってます ⚒ 

ref https://github.com/MotocalDevelopers/motocal/issues/80

**Comment by hsimyu** [comment]
https://travis-ci.org/MotocalDevelopers/motocal 
Activate しました 👍

**Comment by gin0606** [comment]
@hsimyu 
https://travis-ci.org/MotocalDevelopers/motocal/builds/394045199
動いた 👍 
ありがとうございます！！！！！！！！！！！！！！！！！！！！！！！！！！！
