### ISSUE TITLE
failed TravisCI

### ISSUE THREAD

**Issue by sys-cat** [MotocalDevelopers/motocal#99]
https://travis-ci.org/MotocalDevelopers/motocal/builds/394413980#L471

`/home/travis/.travis/job_stages: line 236: ./node_modules/.bin/npm: No such file or directory`

**Comment by hrhyt** [comment]
`cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`

`package-lock.json`をupdateすれば動くと思います。

恐らく`package.json`と`package-lock.json`の不一致です。

`package.json`の中身を更新したのに`package-lock.json`がコミットされなかったということがあったのかもしれません。

**Comment by hrhyt** [comment]
#94 こちらでも同じ問題が出ていました。

**Comment by sys-cat** [comment]
fixed this probrem on finaly #108
